---
abstract: 'Send LWP requests through a caching proxy server'
author:
  - 'Eric Johnson <cpan at iijo dot org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  LWP::UserAgent: 0
  MooseX::Test::Role: 0
  Test::HTTP::Server: 0
  Test::More: 0
  Test::Most: 0
  base: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-CachingProxy
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  MooseX::CachingProxy:
    file: lib/MooseX/CachingProxy.pm
    version: 0.001
requires:
  LWP::Protocol::PSGI: 0
  Moose::Role: 0
  MooseX::Types::Path::Class: 0
  Plack::App::Proxy: 0
  Plack::Builder: 0
  Plack::Middleware::Cache: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/kablamo/MooseX-CachingProxy/issues
  homepage: https://github.com/kablamo/MooseX-CachingProxy
  repository: https://github.com/kablamo/MooseX-CachingProxy.git
version: 0.001
